services:

  storage:
    image: redis
    volumes:
      - ./data:/data

  library:
    image: node:20.10
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3002
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
    command: npm run dev
    depends_on:
      - storage
      
  counter:
    image: node:20.10
    working_dir: /app
    volumes:
      - ../netology-counter-hw:/app
    ports:
      - 82:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    command: npm run dev
    depends_on:
      - storage